spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud
  artemis:
    broker-url: localhost:61617
    user: admin
    password: password
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: password
    template:
      exchange: tacocloud.order
      routing-key: kitchens.central
      receive-timeout: 30000
  # Setting default destination for JMS
  jms:
    template:
      default-destination: tacocloud.order.queue
server:
  port: 8080

# Program properties
taco:
  orders:
    page-size: 20