spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud
server:
  port: 8080

# Program properties
taco:
  orders:
    page-size: 20
tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: password
    poll-rate: 10000
