spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
logging:
  # file:
  #   path: /var/logs
  #   file: TacoCloud.log
  level:
    org:
      springframework:
        root: DEBUG
        web: DEBUG
        security: DEBUG
debug: true
server:
  port: 8080

# Program properties
taco:
  orders:
    page-size: 20